### ISSUE TITLE
A bit of helpful advice to people trying to get the IDs 

### ISSUE THREAD

**Issue by Joshua-Baca** [adrianlois/RedShelf-Bypass-PDFDownload#4]
Just wanted to give a bit of helpful advice to people
I use FireFox, so it likely won't be different for Chrome.

Variables
`base_url = "https://platform.virdocs.com/rscontent/epub/XXXXXXX/XXXXXXX/OEBPS/images/page-{}.jpg"`

To find the base URL in inspect element, search for 

`../images/page-1.jpg`

This will show up as a link, so right-click it click on "Open Link In New Tab" then look at the URL. It should look something like the URL below. 

`https://platform.virdocs.com/private/manifest_item/XXXXXXX/XXXXXXX/YYYYYYYYYYYYYYYYY.jpg?AWSAccessKeyId=YYYYYYYYYYYYYY&Signature=YYYYYYYY&Expires=YYYYYYYYYY`

The spot where I marked it as XXXXXXX will be the two variables that you need. 

Cookies
So, for the session_ID and csrftoken. For the session_ID, there's only one, don't confuse it with "sessionid". On my end I get multiple IDs for the csrftoken, just be sure you get the long csrftoken, it will be basically the same length of the session_ID. 

Hope that helps someone else out.

**Comment by adrianlois** [comment]
> Joshua

Hi, Joshua-Baca

Thanks for the clarification on the usage with Firefox, it really is very similar to Chrome as you rightly say.
