### ISSUE TITLE
Error in doc.build()

### ISSUE THREAD

**Issue by KevinKurtz** [adrianlois/RedShelf-Bypass-PDFDownload#6]
![image](https://github.com/user-attachments/assets/c85737c8-460e-4206-9c1f-78aa5def9e66)
Seems I'm having an error getting the images into the pdf. It collects all the images in a folder and the sort appears to work, but the .build command fails catastrophically. I'm investigating how the simpledoctemplate works to try and fix my issue, but I'm not sure what the base cause is. I'm running in a clean venv with just the required 2 dependencies installed. Python3.

**Comment by KevinKurtz** [comment]
The images are too big because of the padding margins. Makes the images 60 pixels too wide (and whatever aspect ratio bigger in height). You can either subtract 60 from A4[0] in both height and width equations or move the padding to 0. I chose to remove the padding.

I assume this code used to work, why did the old images used in testing not cause this error? Is the padding needed when you have textbook images that already have surrounding white space... probably?

If that's silly let me know. I submitted a PR, but not sure it's necessary. Mine might be an isolated incident.

**Comment by adrianlois** [comment]
> The images are too big because of the padding margins. Makes the images 60 pixels too wide (and whatever aspect ratio bigger in height). You can either subtract 60 from A4[0] in both height and width equations or move the padding to 0. I chose to remove the padding.
> 
> I assume this code used to work, why did the old images used in testing not cause this error? Is the padding needed when you have textbook images that already have surrounding white space... probably?
> 
> If that's silly let me know. I submitted a PR, but not sure it's necessary. Mine might be an isolated incident.

Hi! It is a good consideration, in my tests with those margins it fit correctly, but I don't see it wrong, if the format is A4 there would be no need to add margins.
